#build-job:
# stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"
#
image: registry.gitlab.com/pages/hugo:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo
  artifacts:
    paths:
    - public
  only:
    - $CI_COMMIT_BRANCH
